import '../styles/globals.css'
import { Inter } from 'next/font/google'
import { Providers } from './chakura/providers'
import Navbar from '@/components/layout/navbar/page'
import Footer from '@/components/layout/footer/page'
const inter = Inter({ subsets: ['latin'] })
import 'swiper/css';

import "swiper/css/effect-coverflow";
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
        {children}
          <Footer />
        </Providers>
        </body>
    </html>
  )
}
